apiVersion: apps/v1
kind: Deployment
metadata:
    name: event-dispatcher
    labels:
      app: event-dispatcher
spec:
    replicas: 1
    selector:
      matchLabels:
        app: event-dispatcher
    template:
      metadata:
        labels:
          app: event-dispatcher
      spec:
        containers:
        - name: event-dispatcher
          image: kingaiva/event-dispatcher:stable
          env:
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: smtp-host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: smtp-port
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: smtp-password
            - name: PORT
              value: "8000"
            - name: DEPLOY_TYPE
              value: dev
            - name: MAINTENANCE_STATUS
              valueFrom:
                configMapKeyRef:
                  name: maintenance-config
                  key: status
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: ed-port