FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN python3 -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

RUN pip install fastapi uvicorn yfinance pandas

COPY src/api/main.py /app/main.py
COPY src/core/event_dispatch_functions.py /app/event_dispatch_functions.py

CMD ["python3","main.py"]